version: "3.2"
services:
  users-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PugChat_users_ms_development
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
      - "3309:3306"

  users-ms:
    build: .
    command: rails s -b '0.0.0.0'
    ports:
      - "4002:3000"
